//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.11 at 08:41:06 PM IST 
//


package in.gov.uidai.authentication.common.types._1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AuthErrorClassification.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AuthErrorClassification">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="UID_NOT_FOUND"/>
 *     &lt;enumeration value="UID_INACTIVE"/>
 *     &lt;enumeration value="UID_BLOCKED"/>
 *     &lt;enumeration value="INCORRECT_PIN"/>
 *     &lt;enumeration value="INCORRECT_OTP"/>
 *     &lt;enumeration value="TKN_MISMATCH"/>
 *     &lt;enumeration value="FRAUD_CHECK_FAILED"/>
 *     &lt;enumeration value="NO_BIOMETRIC_GALLERY"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AuthErrorClassification", namespace = "http://www.uidai.gov.in/authentication/common/types/1.0")
@XmlEnum
public enum AuthErrorClassification {

    UID_NOT_FOUND,
    UID_INACTIVE,
    UID_BLOCKED,
    INCORRECT_PIN,
    INCORRECT_OTP,
    TKN_MISMATCH,
    FRAUD_CHECK_FAILED,
    NO_BIOMETRIC_GALLERY;

    public String value() {
        return name();
    }

    public static AuthErrorClassification fromValue(String v) {
        return valueOf(v);
    }

}
