//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.11 at 08:41:06 PM IST 
//


package in.gov.uidai.authentication.uid_auth_request_data._1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BiometricPosition.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="BiometricPosition">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="LEFT_IRIS"/>
 *     &lt;enumeration value="RIGHT_IRIS"/>
 *     &lt;enumeration value="BOTH_IRIS"/>
 *     &lt;enumeration value="LEFT_INDEX"/>
 *     &lt;enumeration value="LEFT_LITTLE"/>
 *     &lt;enumeration value="LEFT_MIDDLE"/>
 *     &lt;enumeration value="LEFT_RING"/>
 *     &lt;enumeration value="LEFT_THUMB"/>
 *     &lt;enumeration value="RIGHT_INDEX"/>
 *     &lt;enumeration value="RIGHT_LITTLE"/>
 *     &lt;enumeration value="RIGHT_MIDDLE"/>
 *     &lt;enumeration value="RIGHT_RING"/>
 *     &lt;enumeration value="RIGHT_THUMB"/>
 *     &lt;enumeration value="BOTH_THUMBS"/>
 *     &lt;enumeration value="LEFT_SLAP"/>
 *     &lt;enumeration value="RIGHT_SLAP"/>
 *     &lt;enumeration value="UNKNOWN"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "BiometricPosition")
@XmlEnum
public enum BiometricPosition {

    LEFT_IRIS,
    RIGHT_IRIS,
    BOTH_IRIS,
    LEFT_INDEX,
    LEFT_LITTLE,
    LEFT_MIDDLE,
    LEFT_RING,
    LEFT_THUMB,
    RIGHT_INDEX,
    RIGHT_LITTLE,
    RIGHT_MIDDLE,
    RIGHT_RING,
    RIGHT_THUMB,
    BOTH_THUMBS,
    LEFT_SLAP,
    RIGHT_SLAP,
    UNKNOWN;

    public String value() {
        return name();
    }

    public static BiometricPosition fromValue(String v) {
        return valueOf(v);
    }

}
