//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.11 at 08:41:06 PM IST 
//


package in.gov.uidai.authentication.uid_auth_request_data._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Locn complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Locn">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="lat" type="{http://www.uidai.gov.in/authentication/uid-auth-request-data/1.0}Latitude" />
 *       &lt;attribute name="lng" type="{http://www.uidai.gov.in/authentication/uid-auth-request-data/1.0}Longitude" />
 *       &lt;attribute name="vtc" type="{http://www.uidai.gov.in/authentication/uid-auth-request-data/1.0}Geocode" />
 *       &lt;attribute name="subdist" type="{http://www.uidai.gov.in/authentication/uid-auth-request-data/1.0}Geocode" />
 *       &lt;attribute name="dist" type="{http://www.uidai.gov.in/authentication/uid-auth-request-data/1.0}Geocode" />
 *       &lt;attribute name="state" type="{http://www.uidai.gov.in/authentication/uid-auth-request-data/1.0}Geocode" />
 *       &lt;attribute name="pc" type="{http://www.uidai.gov.in/authentication/uid-auth-request-data/1.0}Geocode" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Locn")
public class Locn {

    @XmlAttribute
    protected String lat;
    @XmlAttribute
    protected String lng;
    @XmlAttribute
    protected String vtc;
    @XmlAttribute
    protected String subdist;
    @XmlAttribute
    protected String dist;
    @XmlAttribute
    protected String state;
    @XmlAttribute
    protected String pc;

    /**
     * Gets the value of the lat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLat() {
        return lat;
    }

    /**
     * Sets the value of the lat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLat(String value) {
        this.lat = value;
    }

    /**
     * Gets the value of the lng property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLng() {
        return lng;
    }

    /**
     * Sets the value of the lng property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLng(String value) {
        this.lng = value;
    }

    /**
     * Gets the value of the vtc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVtc() {
        return vtc;
    }

    /**
     * Sets the value of the vtc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVtc(String value) {
        this.vtc = value;
    }

    /**
     * Gets the value of the subdist property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubdist() {
        return subdist;
    }

    /**
     * Sets the value of the subdist property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubdist(String value) {
        this.subdist = value;
    }

    /**
     * Gets the value of the dist property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDist() {
        return dist;
    }

    /**
     * Sets the value of the dist property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDist(String value) {
        this.dist = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the pc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPc() {
        return pc;
    }

    /**
     * Sets the value of the pc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPc(String value) {
        this.pc = value;
    }

}
