//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.11 at 08:41:06 PM IST 
//


package in.gov.uidai.authentication.uid_auth_request_data._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Meta complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Meta">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Locn" type="{http://www.uidai.gov.in/authentication/uid-auth-request-data/1.0}Locn" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="fdc" type="{http://www.uidai.gov.in/authentication/uid-auth-request-data/1.0}Code" />
 *       &lt;attribute name="idc" type="{http://www.uidai.gov.in/authentication/uid-auth-request-data/1.0}Code" />
 *       &lt;attribute name="apc" use="required" type="{http://www.uidai.gov.in/authentication/uid-auth-request-data/1.0}Code" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Meta", propOrder = {
    "locn"
})
public class Meta {

    @XmlElement(name = "Locn")
    protected Locn locn;
    @XmlAttribute
    protected String fdc;
    @XmlAttribute
    protected String idc;
    @XmlAttribute(required = true)
    protected String apc;

    /**
     * Gets the value of the locn property.
     * 
     * @return
     *     possible object is
     *     {@link Locn }
     *     
     */
    public Locn getLocn() {
        return locn;
    }

    /**
     * Sets the value of the locn property.
     * 
     * @param value
     *     allowed object is
     *     {@link Locn }
     *     
     */
    public void setLocn(Locn value) {
        this.locn = value;
    }

    /**
     * Gets the value of the fdc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFdc() {
        return fdc;
    }

    /**
     * Sets the value of the fdc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFdc(String value) {
        this.fdc = value;
    }

    /**
     * Gets the value of the idc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdc() {
        return idc;
    }

    /**
     * Sets the value of the idc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdc(String value) {
        this.idc = value;
    }

    /**
     * Gets the value of the apc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApc() {
        return apc;
    }

    /**
     * Sets the value of the apc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApc(String value) {
        this.apc = value;
    }

}
