//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.11 at 08:41:06 PM IST 
//


package in.gov.uidai.authentication.uid_auth_request._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Auth complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Auth">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Tkn" type="{http://www.uidai.gov.in/authentication/uid-auth-request/1.0}Tkn" minOccurs="0"/>
 *         &lt;element name="Skey" type="{http://www.uidai.gov.in/authentication/uid-auth-request/1.0}Skey"/>
 *         &lt;element name="Uses" type="{http://www.uidai.gov.in/authentication/uid-auth-request/1.0}Uses"/>
 *         &lt;element name="Data" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *         &lt;element name="Hmac" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="uid" use="required" type="{http://www.uidai.gov.in/authentication/common/types/1.0}uid" />
 *       &lt;attribute name="ac" use="required" type="{http://www.uidai.gov.in/authentication/uid-auth-request/1.0}AuaCode" />
 *       &lt;attribute name="tid" use="required" type="{http://www.uidai.gov.in/authentication/uid-auth-request/1.0}Tid" />
 *       &lt;attribute name="ver" type="{http://www.uidai.gov.in/authentication/uid-auth-request/1.0}Ver" />
 *       &lt;attribute name="txn" type="{http://www.uidai.gov.in/authentication/uid-auth-request/1.0}Txn" />
 *       &lt;attribute name="lk" type="{http://www.uidai.gov.in/authentication/uid-auth-request/1.0}LicenseKey" />
 *       &lt;attribute name="sa" use="required" type="{http://www.uidai.gov.in/authentication/uid-auth-request/1.0}AuaCode" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Auth", propOrder = {
    "tkn",
    "skey",
    "uses",
    "data",
    "hmac"
})
public class Auth {

    @XmlElement(name = "Tkn")
    protected Tkn tkn;
    @XmlElement(name = "Skey", required = true)
    protected Skey skey;
    @XmlElement(name = "Uses", required = true)
    protected Uses uses;
    @XmlElement(name = "Data", required = true)
    protected byte[] data;
    @XmlElement(name = "Hmac")
    protected byte[] hmac;
    @XmlAttribute(required = true)
    protected String uid;
    @XmlAttribute(required = true)
    protected String ac;
    @XmlAttribute(required = true)
    protected String tid;
    @XmlAttribute
    protected String ver;
    @XmlAttribute
    protected String txn;
    @XmlAttribute
    protected String lk;
    @XmlAttribute(required = true)
    protected String sa;

    /**
     * Gets the value of the tkn property.
     * 
     * @return
     *     possible object is
     *     {@link Tkn }
     *     
     */
    public Tkn getTkn() {
        return tkn;
    }

    /**
     * Sets the value of the tkn property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tkn }
     *     
     */
    public void setTkn(Tkn value) {
        this.tkn = value;
    }

    /**
     * Gets the value of the skey property.
     * 
     * @return
     *     possible object is
     *     {@link Skey }
     *     
     */
    public Skey getSkey() {
        return skey;
    }

    /**
     * Sets the value of the skey property.
     * 
     * @param value
     *     allowed object is
     *     {@link Skey }
     *     
     */
    public void setSkey(Skey value) {
        this.skey = value;
    }

    /**
     * Gets the value of the uses property.
     * 
     * @return
     *     possible object is
     *     {@link Uses }
     *     
     */
    public Uses getUses() {
        return uses;
    }

    /**
     * Sets the value of the uses property.
     * 
     * @param value
     *     allowed object is
     *     {@link Uses }
     *     
     */
    public void setUses(Uses value) {
        this.uses = value;
    }

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setData(byte[] value) {
        this.data = ((byte[]) value);
    }

    /**
     * Gets the value of the hmac property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getHmac() {
        return hmac;
    }

    /**
     * Sets the value of the hmac property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setHmac(byte[] value) {
        this.hmac = ((byte[]) value);
    }

    /**
     * Gets the value of the uid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUid() {
        return uid;
    }

    /**
     * Sets the value of the uid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUid(String value) {
        this.uid = value;
    }

    /**
     * Gets the value of the ac property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAc() {
        return ac;
    }

    /**
     * Sets the value of the ac property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAc(String value) {
        this.ac = value;
    }

    /**
     * Gets the value of the tid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTid() {
        return tid;
    }

    /**
     * Sets the value of the tid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTid(String value) {
        this.tid = value;
    }

    /**
     * Gets the value of the ver property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVer() {
        return ver;
    }

    /**
     * Sets the value of the ver property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVer(String value) {
        this.ver = value;
    }

    /**
     * Gets the value of the txn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxn() {
        return txn;
    }

    /**
     * Sets the value of the txn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxn(String value) {
        this.txn = value;
    }

    /**
     * Gets the value of the lk property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLk() {
        return lk;
    }

    /**
     * Sets the value of the lk property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLk(String value) {
        this.lk = value;
    }

    /**
     * Gets the value of the sa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSa() {
        return sa;
    }

    /**
     * Sets the value of the sa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSa(String value) {
        this.sa = value;
    }

}
